### ISSUE TITLE
Traceback while extracting keys.

### ISSUE THREAD

**Issue by vikkstar12** [WHTJEON/narrowvine#19]
getting this error:

###Traceback (most recent call last):
  File "google\protobuf\internal\python_message.py", line 1145, in MergeFromString
  File "google\protobuf\internal\python_message.py", line 1198, in InternalParse
  File "google\protobuf\internal\decoder.py", line 989, in _DecodeUnknownField
  File "google\protobuf\internal\decoder.py", line 963, in _DecodeUnknownFieldSet
  File "google\protobuf\internal\decoder.py", line 192, in ReadTag
IndexError: index out of bounds on dimension 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\Mac\Home\vliveplus-dl\VLIVEPLUS_POC\narrowvine.py", line 246, in <module>
  File "\\Mac\Home\vliveplus-dl\VLIVEPLUS_POC\narrowvine.py", line 113, in getkeys
  File "\\Mac\Home\vliveplus-dl\VLIVEPLUS_POC\narrowvine.py", line 108, in work
  File "\\Mac\Home\vliveplus-dl\VLIVEPLUS_POC\narrowvine.py", line 81, in getContentKey
  File "google\protobuf\message.py", line 199, in ParseFromString
  File "google\protobuf\internal\python_message.py", line 1151, in MergeFromString
google.protobuf.message.DecodeError: Truncated message.
[600] Failed to execute script  #narrowvine###

**Comment by WHTJEON** [comment]
It is revoked by Widevine as expected.
